Repository modeso-open-source/1lims-automation, pull requests merged in 2020-06, with the labels that each got.

#255 LIMS-5816: duplicate order/suborder with multiple contacts
  .travis.yml
  api_testing/apis/orders_api.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/base_test.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#253 LIMS-6222: Duplicate main order then change the contact
  .travis.yml
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#261 Lims/3267
  .travis.yml
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#204 Lims 3406
  .travis.yml
  .travis_stable.yml
  config.ini
  ui_testing/elements.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#231 LIMS-4269: edit suborder test unit
  .travis.yml
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  api_testing/apis/test_unit_api.py
  ui_testing/pages/base_pages.py
  ui_testing/pages/base_selenium.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#251 LIMS-4134: update suborder with multiple testPlans_delete_approach
  .travis.yml
  api_testing/apis/article_api.py
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  ui_testing/elements.py
  ui_testing/pages/analyses_page.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#242 LIMS-3495: order filter
  .travis.yml
  api_testing/apis/contacts_api.py
  api_testing/apis/orders_api.py
  screenshot_test020_filter_by_department.png
  ui_testing/elements.py
  ui_testing/pages/base_pages.py
  ui_testing/pages/base_selenium.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/base_test.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: RedTravis

#209 Lims 4349
  .travis.yml
  ui_testing/elements.py
  ui_testing/pages/base_pages.py
  ui_testing/pages/order_page.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#234 Lims 3710: Orders: Archived Test unit: Archive Approach: Archived test units shouldn't appear in orders in the drop down list
  .travis.yml
  .travis_stable.yml
  api_testing/apis/test_unit_api.py
  screenshot_test035_archived_test_unit_shoudnt_display_in_the_order_drop_down_list.png
  ui_testing/pages/order_page.py
  ui_testing/pages/testunits_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#250 LIMS-6232: Duplicate sub order with multiple test units and test plans then add test unit & test plan
  .github/workflows/CI.yml
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  screenshot_test042_table_with_add_edit_single_row.png
  screenshot_test042_table_with_add_edit_single_row00.png
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#171 My profile upload and save
  .github/workflows/CI.yml
  api_testing/apis/base_api.py
  ui_testing/elements.py
  ui_testing/pages/base_pages.py
  ui_testing/pages/base_selenium.py
  ui_testing/pages/header_page.py
  ui_testing/pages/my_profile_page.py
  ui_testing/testcases/base_test.py
  ui_testing/testcases/basic_tests/test06_orders.py
  ui_testing/testcases/header_tests/test09_my_profile.py
Labels: RedActions

#247 LIMS-6221 and LIMS-6229:: Duplicate main/sub order with one testPlan and testUnit then change them
  .github/workflows/CI.yml
  api_testing/apis/test_plan_api.py
  ui_testing/pages/analyses_page.py
  ui_testing/pages/order_page.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#262 LIMS-4267: edit order material type
  .github/workflows/CI.yml
  api_testing/apis/test_plan_api.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#270 create order using api
  .github/workflows/CI.yml
  api_testing/apis/article_api.py
  api_testing/apis/orders_api.py
Labels: ready for review

#271 create_order in order_page.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test03_testplans.py
  ui_testing/testcases/basic_tests/test05_contacts.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#275 LIMS-4270: update_order_no_should_reflect_all_suborders_and_analysis
  .github/workflows/CI.yml
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#272 Lims 4796: Testplans_popup
  .github/workflows/CI.yml
  screenshot_test044_edit.png
  ui_testing/elements.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#273 LIMS-6933 & 8258: Upload attachments
  .github/workflows/CI.yml
  ui_testing/elements.py
  ui_testing/pages/base_pages.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#276 LIMS-7427: Make sure that you can search by all the year format
  .github/workflows/CI.yml
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: ready for review

#278 Lims 8085: single order only
  .travis.yml
  screenshot_test040_download_order_sheet.png
  screenshot_test040_download_suborder_sheet_for_single_order.png
  ui_testing/pages/base_pages.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/base_test.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: RedActions

#264 LIMS-5704: add department in case of multiple contacts' order in creat and edit modes
  .travis.yml
  api_testing/apis/contacts_api.py
  api_testing/apis/orders_api.py
  ui_testing/pages/order_page.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test06_orders.py
Labels: help wanted
