Repository modeso-open-source/1lims-automation, pull requests merged in 2020-09, with the labels that each got.

#326 LIMS-5810 : Allow user to see the sub & super scripts in the export file ( quantitative MiBi )
  .github/workflows/execution.sh
  ui_testing/testcases/basic_tests/test004_testunits.py
Labels: ready for merging

#329 LIMS-6812 :Test unit : click overview from test unit edit page (check pop up)
  .github/workflows/execution.sh
  ui_testing/pages/base_pages.py
  ui_testing/pages/testunit_page.py
  ui_testing/testcases/basic_tests/test003_testplans.py
  ui_testing/testcases/basic_tests/test004_testunits.py
Labels: ready for merging

#347 LIMS-5794 : Active table/unit: Sub & Super scripts: Allow unit to display with sub & super scripts in the active table
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/testcases/basic_tests/test004_testunits.py
Labels: ready for merging

#365 LIMS-5404 : [Archiving][MainOrder]Make sure that if user cancel archive order,No order or suborders or analysis of the order will be archived
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/elements.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#357 LIMS-6491 and 6492: Contact Gender Story
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/contacts_api.py
  ui_testing/pages/contact_page.py
  ui_testing/pages/contacts_page.py
  ui_testing/testcases/basic_tests/test005_contacts.py
Labels: ready for review

#371 LIMS-7415 : Orders: Ordering test units: Test units in the analysis section should display in the same order as in the order section
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/orders_api.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#364 LIMS-4258: create multiple suborders with diff departments
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  screenshots/screenshot_test085_add_multiple_suborders_with_diff_departments_.png
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#367 LIMS-4276: add suborder with multiple test plans only
  .github/workflows/CI.yml
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#368 LIMS-4247: create multiple suborders with testplan and test unit
  ui_testing/elements.py
  ui_testing/pages/analysis_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#374 LIMS-6626: Update contact config to number in order create form
  api_testing/apis/orders_api.py
  api_testing/config/order_contact_number.json
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#378 LIMS-6672: Test unit name configuration with two fields reflects on create new order
  api_testing/config/testUnit.json
  ui_testing/pages/base_selenium.py
  ui_testing/pages/order_page.py
  ui_testing/pages/testunits_page.py
  ui_testing/testcases/basic_tests/test004_testunits.py
Labels: ready for review

#375 LIMS-5369 : archive suborder
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#382 'LIMS:4795'
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  screenshots/screenshot_test085_add_multiple_suborders_with_diff_departments_.png
  ui_testing/elements.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#372 LIMS-5650 - Test unit: Configuration: make sure that when you select from test unit name configuration drop down list and press on cancel button, nothing changed
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  .gitignore
  ui_testing/elements.py
  ui_testing/pages/testunit_page.py
  ui_testing/testcases/basic_tests/test004_testunits.py
Labels: ready for review

#387 LIMS-4354:Order: Add Same test units in different test plan
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/base_api.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#380 LIMS-7416: Ordering test units Approach: In case I put test plans an…
  api_testing/apis/test_plan_api.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#385 LIMS-7426: filter by order no contains "-2020"
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#386 LIMS-5818:Orders: Create: Create from existing: Old order should change when contact is updated
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  screenshots/screenshot_test074_create_existing_order_change_contact_.png
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#388 LIMS-6666: Order: Testunit search approach; allow user to search with testunit name/method/unit/number in order form
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#392 LIMS-7425 : Filter: Analysis number format: In case the analysis number displayed with full year, I can filter by it
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/elements.py
  ui_testing/pages/analyses_page.py
  ui_testing/pages/base_pages.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#393 LIMS-4256: create suborders with multiple test plans & units
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#394 LIMS-7424 and LIMS-7423: year-format downloaded in sheet
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#408 LIMS-3253: article disable using API
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/article_api.py
  api_testing/apis/base_api.py
  api_testing/apis/general_utilities_api.py
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  api_testing/apis/test_unit_api.py
  api_testing/end_points.py
  screenshots/screenshot_test074_create_existing_order_change_contact_.png
  ui_testing/elements.py
  ui_testing/pages/base_pages.py
  ui_testing/pages/header_page.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
  ui_testing/testcases/extended_tests/test001_order.py
Labels: ready for review

#395 LIMS-5379: order filter feilds
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/elements.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#406 LIMS-7411 and 7444: test unit configuration affect on order filter
  .github/workflows/execution.sh
  api_testing/apis/test_unit_api.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#419 LIMS-5358:[Orders][Active table] Make sure that list menu will contain ( COA,Archive , XSLX - Archived - Configurations) Only
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/elements.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#404 LIMS-5361:Orders: Restore Approach: User can restore any order from the archived table
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/base_api.py
  api_testing/apis/orders_api.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#409 LIMS-7414: test unit configuration to 2 field reflect on create order form
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/testcases/basic_tests/test004_testunits.py
Labels: ready for review

#417 LIMS-6289: Empty unit field downloaded as '-' in test unit XSXL sheet
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/testcases/basic_tests/test004_testunits.py
Labels: ready for review

#418 LIMS-5356 and LIMS-5357: check child table exist then duplicate from table with add
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#420 Lims 6816: edit contact then press overview button
  ui_testing/testcases/basic_tests/test005_contacts.py
Labels: ready for review

#416 LIMS-6632: Orders: Contact configuration approach: In case the user configures the contact field to display name & number this action should reflect on the order active table
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  ui_testing/elements.py
  ui_testing/pages/articles_page.py
  ui_testing/pages/contacts_page.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#389 LIMS 4350 :Orders: Create: Orders Choose test plans without test units
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/article_api.py
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  ui_testing/pages/order_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for merging

#384 LIMS-6296: create 2 suborders with two testplans of same name
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/article_api.py
  api_testing/apis/orders_api.py
  api_testing/apis/test_plan_api.py
  ui_testing/pages/analysis_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#424 LIMS-5220: Allow user to add any number of the suborders records not only 5 suborders
  .github/workflows/execution.sh
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#423 LIMS-6814 & LIMS-6821:Orders: Popup should appear when editing then clicking on overview without saving <All data will be lost>, No popup should appear when clicking on overview without changing anything
  .github/workflows/execution.sh
  ui_testing/pages/base_pages.py
  ui_testing/testcases/basic_tests/test006_orders.py
Labels: ready for review

#426 LIMS-7729:Orders: Validation date & Validation by : check that when user update the validation date & the validation by, the update should reflect on order's child table
  .github/workflows/CI.yml
  .github/workflows/execution.sh
  api_testing/apis/article_api.py
  api_testing/apis/orders_api.py
  ui_testing/elements.py
  ui_testing/pages/analysis_page.py
  ui_testing/pages/orders_page.py
  ui_testing/testcases/basic_tests/test006_orders.py
  ui_testing/testcases/extended_tests/test001_order.py
Labels: question, ready for merging
